### ISSUE TITLE
failing tests 

### ISSUE THREAD

**Issue by patroqueeet** [Develatio/django-walletpass#10]
due to https://github.com/python-hyper/hyper/issues/431. the `hyper` project is not maintained... https://github.com/python-hyper/hyper

**Comment by NachE** [comment]
this also affect to APNsClient https://github.com/Pr0Ger/PyAPNs2/issues/126

**Comment by patroqueeet** [comment]
@NachE the pyapns2 progress is quite slow. switch to aioapns?

**Comment by NachE** [comment]
I am open to any ideas. Is this lib up to date enough?

**Comment by patroqueeet** [comment]
sent already https://github.com/Develatio/django-walletpass/pull/15 . awaiting feedback.

**Comment by NachE** [comment]
I have some questions:
- Is python 3.8.0 really needed?
- This PR finally remove cert auth and the only way to authenticate is throught token?

**Comment by patroqueeet** [comment]
fixed now
