### ISSUE TITLE
Support Django 4.2+

### ISSUE THREAD

**Issue by alexandernst** [Develatio/django-walletpass#32]
This app, as it is, won't work with Django 4.2+ because of a deprecation that django did regarding the way `DEFAULT_FILE_STORAGE` works. 

https://docs.djangoproject.com/en/5.0/releases/4.2/#custom-file-storages

**Comment by patroqueeet** [comment]
hm, running it here w/ 4.2 without any probs. 🤔

**Comment by alexandernst** [comment]
My bad. It only got **deprecated** in 4.2, not removed. Still, we should migrate to the new `STORAGES` setting as the previous behavior will get removed eventually.

**Comment by patroqueeet** [comment]
@alexandernst will you make a PR?

**Comment by alexandernst** [comment]
@patroqueeet  Not sure 🤔, currently I don't have any spare time to dedicate to this. If nobody beats me to it, I'll eventually patch it, but it might not be soon.

**Comment by patroqueeet** [comment]
ack, should we do a quick release to get the latest changes out @alexandernst ?

**Comment by alexandernst** [comment]
I already did, yesterday! 🤟😁

**Comment by patroqueeet** [comment]
👏

**Comment by patroqueeet** [comment]
@alexandernst closable after #40 ?

**Comment by alexandernst** [comment]
Yes, this is closable :) . Do the honors! 🙏

**Comment by patroqueeet** [comment]
done with #40
