### ISSUE TITLE
RegisterPassViewSet: destroy method not deleting registration if found.

### ISSUE THREAD

**Issue by GonzaloMachado** [Develatio/django-walletpass#33]
Hi again!

I have been testing the library and I came across an issue in the RegisterPassViewSet class.

In the destroy method of **RegisterPassViewSet**,  if a registration is found, it responds with a 200 OK but does not delete the registration. I believe there might be a logical error in the code.

    def destroy(self, request, device_library_id, pass_type_id, serial_number):
        pass_ = get_pass(pass_type_id, serial_number)
        if request.META.get('HTTP_AUTHORIZATION') != f"ApplePass {pass_.authentication_token}":
            return Response({}, status=status.HTTP_401_UNAUTHORIZED)
        registration = Registration.objects.filter(
            device_library_identifier=device_library_id,
            pazz=pass_,
        )
        if registration:
            return Response({}, status=status.HTTP_200_OK)
        registration.delete()
        PASS_UNREGISTERED.send(sender=pass_)
        return Response({}, status=status.HTTP_200_OK)

**Suggested Correction**
Shouldn't the condition be if **not** registration: to ensure that the registration is deleted if found in the queryset? As it currently stands, the pass is not deleted if it is found in the queryset.

**Steps to Reproduce**

1. Register a device to receive push notifications for a pass.
2. Attempt to unregister the device using the destroy method.
3. Observe that the registration is not deleted,  just a 200 OK response is returned.

**Expected Behavior**
The registration should be deleted when a POST request is made to the destroy method, provided the registration is found in the queryset.

Thank you for your attention to this matter. Please let me know if you need any additional information.

**Comment by patroqueeet** [comment]
good morning, that would match my observation that we have not enought deletions and some pass update sends failed w/ 'no pass existing'. can you send a PR w/ tests?

**Comment by GonzaloMachado** [comment]
@patroqueeet Thank you for bringing this to my attention. I'll be posting the changes along with the tests later this week or next week, as I'm currently busy with other projects. TTYS.

**Comment by alexandernst** [comment]
Fixed by https://github.com/Develatio/django-walletpass/pull/36
