### ISSUE TITLE
auto-update unregistered registrations

### ISSUE THREAD

**Issue by patroqueeet** [Develatio/django-walletpass#38]
use `aioapns` `err_func` to automatically remove registrations when return code `410` is being retrieved. requires `aioapns` v3+

probably we want to be able to disable/enable through setting

**Comment by patroqueeet** [comment]
@alexandernst @NachE good idea? do we want to add this?

**Comment by NachE** [comment]
It seems like a good idea to me

**Comment by patroqueeet** [comment]
done and merged.
