### ISSUE TITLE
timezone ignored in API

### ISSUE THREAD

**Issue by patroqueeet** [Develatio/django-walletpass#4]
https://github.com/Develatio/django-walletpass/blob/b54f5a5f4f95a092ab3a4d395b40c83a0c9872a9/django_walletpass/classviews.py#L40

ignores the timezone, but actually Apple does care about.

example:

```
In [50]: Log.objects.order_by('-pk')[3].message
Out[50]: "[2020-11-16 21:46:34 +0100] Web service error for pass.ch.darg (https://www.das-aktienregister.ch/api/passes): Response to 'What changed?' request included 1 serial numbers but the lastUpdated tag (2020-11-16 20:46:33) remained the same."
```

fails because, the models `updated_at` is in UTC as is the local systems time. but the log reports +1hr

that results into wrong IDs reported to Apple.

**Comment by patroqueeet** [comment]
@NachE with this one, we now should be up to date with this little lib... to recent update needs and small fixes

https://github.com/Develatio/django-walletpass/pull/9

**Comment by alexandernst** [comment]
Merged in https://github.com/Develatio/django-walletpass/pull/9
