### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by patroqueeet** [Develatio/django-walletpass#5]
Hey, this lib would be happy about py3.5+ compatibility and some comments on the issues... if not maintained: pls document and offer to handover...

**Comment by alexandernst** [comment]
Hey! We're currently not maintaining this library, but if you're willing to work on it we can grant you write permissions on the repo (after a few PRs).

**Comment by patroqueeet** [comment]
alright. might be a way, as I'm using it actively. when heading towards Django4 with my project I will probably get back and send some PRs. But this might take a while.

or do you want to recommend a more suitable py lib as of now? what are you using?

**Comment by alexandernst** [comment]
I'm not aware of any other libs that implement Apple's walletpass (but they might exist, of course).

**Comment by patroqueeet** [comment]
ack. I checked them before, but yours looked best. :)

**Comment by patroqueeet** [comment]
ttyl!

**Comment by patroqueeet** [comment]
well, looks like in 2023 it is :)
